In [ ]:
import jax
import jax.numpy as jnp
arr = jnp.arange(32.0).reshape(4, 8)
arr.devices()

{CpuDevice(id=0)}

In [2]:
arr.sharding

SingleDeviceSharding(device=CpuDevice(id=0), memory_kind=unpinned_host)

In [4]:
jax.debug.visualize_array_sharding(arr)

┌────────────────────────────────────────────────┐
│                                                │
│                                                │
│                                                │
│                                                │
│                     CPU 0                      │
│                                                │
│                                                │
│                                                │
│                                                │
└────────────────────────────────────────────────┘

In [6]:
from jax.sharding import PartitionSpec as P
mesh = jax.make_mesh((1,), ('x'))
sharding = jax.sharding.NamedSharding(mesh, P('x'))
print(sharding)

NamedSharding(mesh=Mesh('x': 1), spec=PartitionSpec('x',), memory_kind=unpinned_host)


In [7]:
arr_sharded = jax.device_put(arr, sharding)

print(arr_sharded)
jax.debug.visualize_array_sharding(arr_sharded)

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29. 30. 31.]]


┌────────────────────────────────────────────────┐
│                                                │
│                                                │
│                                                │
│                                                │
│                     CPU 0                      │
│                                                │
│                                                │
│                                                │
│                                                │
└────────────────────────────────────────────────┘