In [1]:
import jax
import jax.numpy as jnp
from collections import namedtuple


def plus(aa:dict, arr:jnp.ndarray):
    return arr.at[0].add(aa["data"])

arr = jnp.ones(10)
ans = plus({"data": 5}, arr)

print(ans)


[6. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [2]:
input_dict = {"data": 5, "other": 3}
arr = jnp.arange(20).reshape((4, 5))

plus_fn = jax.jit(plus)

ans = jax.vmap(plus_fn, in_axes=(None, 0), out_axes=0)(input_dict, arr)

print(ans)

[[ 5  1  2  3  4]
 [10  6  7  8  9]
 [15 11 12 13 14]
 [20 16 17 18 19]]


In [3]:
from dataclasses import dataclass

@dataclass(frozen=True)
class Data:
    data: int
    extra: int = 0

input_data = Data(data=5)

def plus(aa:Data, arr:jnp.ndarray):
    return arr.at[0].add(aa.data)

arr = jnp.arange(20).reshape((4, 5))
plus_fn = jax.jit(plus, static_argnames="aa")
ans = jax.vmap(
    plus_fn, 
    in_axes=(None, 0), 
    out_axes=0
)(input_data, arr)

print(ans)

[[ 5  1  2  3  4]
 [10  6  7  8  9]
 [15 11 12 13 14]
 [20 16 17 18 19]]


In [9]:
from dataclasses import dataclass
import jax.numpy as jnp

@dataclass(frozen=True)
class Minimap:
    # size: tuple = (9, 9)
    size: jnp.ndarray = jnp.array([9, 9])
    margin: int = 1


@dataclass(frozen=True)
class Fish:
    name: str
    mother_name: str
    max_health: float
    food_rate: float
    land_penalty_rate: float
    move_penalty_rate: float
    health_decay_rate: float

@dataclass(frozen=True)
class Neuron:
    type: str = "neuron"
    refractory_period: float = 1.2
    baseline_rate: float = 0.0

@dataclass(frozen=True)
class Eye:
    eye_direction: str
    rf_positions: jnp.ndarray
    rf_weights: jnp.ndarray
    type: str = "eye"
    input_type: str = "terrain"
    gain: float = 0.5
    refractory_period: float = 1.2
    baseline_rate: float = 0.0

@dataclass(frozen=True)
class Muscle:
    direction: str
    step_motion: jnp.ndarray
    type: str = "muscle"
    refractory_period: float = 1.2
    baseline_rate: float = 0.0


ValueError: mutable default <class 'jaxlib.xla_extension.ArrayImpl'> for field size is not allowed: use default_factory

In [8]:
eye = Eye(
    type="eye"
)

TypeError: Eye.__init__() missing 7 required positional arguments: 'refractory_period', 'baseline_rate', 'input_type', 'eye_direction', 'gain', 'rf_positions', and 'rf_weights'